[package]
name = "LianLianKan"
version = "0.1.0"
authors = ["chengkun <276128749@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#https://crates.io/

rand = "0.6.0"
